<template>
  <div class="admin-page"><NavBar /><main class="content-container"><section class="manage-card">
    <header class="page-header"><h1>组队治理</h1><p>处理队伍异常、举报与推荐配置</p></header>
    <el-tabs v-model="tab" class="manage-tabs">
      <el-tab-pane label="队伍管理" name="teams">
        <div class="filters"><el-input v-model="query.keyword" :prefix-icon="Search" placeholder="队伍、竞赛或负责人学号" clearable @keyup.enter="loadTeams" /><el-select v-model="query.status" placeholder="全部状态" clearable><el-option v-for="s in statuses" :key="s.value" :label="s.label" :value="s.value" /></el-select><el-button type="primary" @click="loadTeams">查询</el-button></div>
        <el-table :data="data.list" v-loading="loading" stripe class="desktop-table"><el-table-column prop="competitionName" label="竞赛" min-width="220" /><el-table-column prop="name" label="队伍" min-width="150" /><el-table-column label="负责人" min-width="150"><template #default="{row}">{{ row.leaderName }} · {{ row.leaderNumber }}</template></el-table-column><el-table-column label="人数" width="90"><template #default="{row}">{{ row.memberCount }}/{{ row.targetSize }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="statusType(row.status)">{{ statusText(row.status) }}</el-tag></template></el-table-column><el-table-column label="操作" min-width="260"><template #default="{row}"><el-button v-if="row.status==='locked'" link type="warning" @click="act(row,'unlock')">解锁</el-button><el-button v-if="!['removed','dissolved'].includes(row.status)" link type="danger" @click="act(row,'remove',true)">下架</el-button><el-button v-if="row.status==='removed'" link type="success" @click="act(row,'restore')">恢复</el-button><el-button v-if="row.status!=='dissolved'" link type="danger" @click="act(row,'dissolve',true)">解散</el-button><el-button link @click="audit(row)">日志</el-button></template></el-table-column></el-table>
        <div class="mobile-list"><article v-for="row in data.list" :key="row.teamId" class="mobile-item"><strong>{{ row.name }}</strong><span>{{ row.competitionName }} · {{ row.leaderName }}</span><span>{{ statusText(row.status) }} · {{ row.memberCount }}/{{ row.targetSize }} 人</span><div><el-button v-if="row.status==='locked'" @click="act(row,'unlock')">解锁</el-button><el-button v-if="row.status==='removed'" @click="act(row,'restore')">恢复</el-button><el-button v-if="!['removed','dissolved'].includes(row.status)" type="danger" plain @click="act(row,'remove',true)">下架</el-button><el-button @click="audit(row)">日志</el-button></div></article></div>
        <el-pagination v-if="data.total" layout="prev,pager,next,total" :total="data.total" :page-size="data.pageSize" v-model:current-page="data.page" @current-change="loadTeams" />
      </el-tab-pane>
      <el-tab-pane name="reports"><template #label>举报处理 <el-badge :value="pendingReports" :hidden="!pendingReports" /></template><el-table :data="reports" v-loading="loading" stripe><el-table-column prop="teamName" label="队伍" /><el-table-column prop="reporter" label="举报人" width="140" /><el-table-column prop="reason" label="原因" min-width="220" /><el-table-column prop="status" label="状态" width="100" /><el-table-column label="操作" width="160"><template #default="{row}"><template v-if="row.status==='pending'"><el-button link type="success" @click="resolve(row,'resolved')">处理</el-button><el-button link @click="resolve(row,'rejected')">驳回</el-button></template></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="推荐权重" name="weights"><p class="hint">权重由管理员统一设置，总和必须为 100。学生只看到命中的推荐理由；技能标签始终标明为学生自填。</p><div class="weight-grid"><el-form-item v-for="field in weightFields" :key="field.key" :label="field.label"><el-input-number v-model="weights[field.key]" :min="0" :max="100" /></el-form-item></div><div class="weight-actions"><span :class="{invalid:weightTotal!==100}">当前合计：{{ weightTotal }}/100</span><el-button type="primary" :disabled="weightTotal!==100" :loading="saving" @click="saveWeights">保存权重</el-button></div><el-divider content-position="left">历史版本</el-divider><el-table :data="weightHistory" size="small"><el-table-column prop="version" label="版本" width="70" /><el-table-column label="技能/岗位/时间/经历/专业年级"><template #default="{row}">{{ row.skillWeight }}/{{ row.roleWeight }}/{{ row.timeWeight }}/{{ row.experienceWeight }}/{{ row.backgroundWeight }}</template></el-table-column><el-table-column prop="createTime" label="更新时间" min-width="170" /></el-table></el-tab-pane>
    </el-tabs>
  </section></main><el-drawer v-model="auditVisible" title="操作日志" size="min(560px,95vw)"><el-timeline><el-timeline-item v-for="item in logs" :key="item.auditId" :timestamp="format(item.createTime)"><strong>{{ item.action }}</strong><p>{{ item.operator }} · {{ item.detail||'无补充说明' }}</p></el-timeline-item></el-timeline></el-drawer></div>
</template>
<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {Search} from '@element-plus/icons-vue'
import NavBar from '../components/NavBar.vue'
import request from '../utils/request'
const tab=ref('teams'),loading=ref(false),saving=ref(false),auditVisible=ref(false),logs=ref([]),reports=ref([]),weightHistory=ref([])
const query=reactive({keyword:'',status:''}),data=reactive({list:[],total:0,page:1,pageSize:20}),weights=reactive({skillWeight:40,roleWeight:20,timeWeight:15,experienceWeight:15,backgroundWeight:10,version:1})
const weightFields=[{key:'skillWeight',label:'技能匹配'},{key:'roleWeight',label:'期望岗位'},{key:'timeWeight',label:'每周时间'},{key:'experienceWeight',label:'认证经历'},{key:'backgroundWeight',label:'专业年级'}]
const weightTotal=computed(()=>weightFields.reduce((sum,field)=>sum+Number(weights[field.key]||0),0))
const statuses=[{label:'招募中',value:'recruiting'},{label:'已成队',value:'closed'},{label:'已锁定',value:'locked'},{label:'已下架',value:'removed'},{label:'已解散',value:'dissolved'}]
const statusText=s=>statuses.find(v=>v.value===s)?.label||s
const statusType=s=>({recruiting:'success',closed:'info',locked:'warning',removed:'danger',dissolved:'info'}[s]||'info')
const pendingReports=computed(()=>reports.value.filter(v=>v.status==='pending').length)
const unwrap=r=>{if(r.code!=='200')throw new Error(r.msg||'操作失败');return r.data}
async function loadTeams(){loading.value=true;try{Object.assign(data,unwrap(await request.get('/api/admin/teams',{params:{...query,page:data.page,pageSize:data.pageSize}})))}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
async function loadReports(){try{reports.value=unwrap(await request.get('/api/admin/teams/reports'))}catch(e){ElMessage.error(e.message)}}
async function loadWeights(){try{Object.assign(weights,unwrap(await request.get('/api/admin/teams/recommendation-weights')));weightHistory.value=unwrap(await request.get('/api/admin/teams/recommendation-weights/history'))}catch(e){ElMessage.error(e.message)}}
async function saveWeights(){saving.value=true;try{Object.assign(weights,unwrap(await request.put('/api/admin/teams/recommendation-weights',weights)));ElMessage.success('推荐权重已更新');await loadWeights()}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
async function act(row,action,reasonNeeded=false){try{let reason='';if(reasonNeeded){const result=await ElMessageBox.prompt('请输入处理原因','治理操作',{inputValidator:v=>!!v.trim()||'请输入原因'});reason=result.value}else await ElMessageBox.confirm('确认执行该操作？','治理操作');unwrap(await request.post(`/api/admin/teams/${row.teamId}/${action}`,{reason}));ElMessage.success('操作已完成');loadTeams()}catch(e){if(e!=='cancel')ElMessage.error(e.message||'操作失败')}}
async function resolve(row,status){try{const result=await ElMessageBox.prompt('填写处理说明','处理举报',{inputValidator:v=>!!v.trim()||'请输入处理说明'});unwrap(await request.post(`/api/admin/teams/reports/${row.reportId}`,{status,resolution:result.value}));ElMessage.success('举报已处理');loadReports()}catch(e){if(e!=='cancel')ElMessage.error(e.message||'处理失败')}}
async function audit(row){try{logs.value=unwrap(await request.get(`/api/admin/teams/${row.teamId}/audit`));auditVisible.value=true}catch(e){ElMessage.error(e.message)}}
const format=v=>new Date(v).toLocaleString('zh-CN')
onMounted(()=>Promise.allSettled([loadTeams(),loadReports(),loadWeights()]))
</script>
<style scoped>
.admin-page{min-height:100vh;color:#1e293b}.content-container{max-width:1320px;margin:auto;padding:40px 20px}.manage-card{padding:0 24px 24px;background:rgba(255,255,255,.65);backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,.85);border-radius:20px;box-shadow:0 10px 30px -10px rgba(15,23,42,.08)}.page-header{padding:24px 4px 16px}.page-header h1{font-size:22px;margin:0 0 6px}.page-header p,.hint{color:#64748b}.filters{display:grid;grid-template-columns:2fr 1fr auto;gap:12px;margin:10px 0 20px;padding:16px 20px;background:rgba(255,255,255,.45);border:1px solid rgba(255,255,255,.7);border-radius:16px}.filters :deep(.el-input__wrapper),.filters :deep(.el-select__wrapper){border-radius:12px;background:rgba(248,250,252,.8);box-shadow:0 0 0 1px #e2e8f0 inset}.filters :deep(.el-button--primary),.weight-actions :deep(.el-button--primary){border:0;border-radius:10px;background:linear-gradient(135deg,#6366f1,#818cf8)}:deep(.el-table){border-radius:16px;overflow:hidden;background:transparent;--el-table-border-color:rgba(226,232,240,.45)}:deep(.el-table th.el-table__cell){height:54px;color:#475569;font-weight:700;background:rgba(248,250,252,.82)}.el-pagination{margin-top:18px;justify-content:flex-end}.weight-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px 20px;margin-top:24px}.weight-actions{display:flex;align-items:center;gap:18px;margin:18px 0}.weight-actions .invalid{color:#dc2626}.mobile-list{display:none}.el-timeline p{color:#68737d;margin:5px 0}@media(max-width:640px){.content-container{padding:18px 12px}.manage-card{padding:0 12px 18px;border-radius:16px}.filters,.weight-grid{grid-template-columns:1fr;padding:14px}.desktop-table{display:none}.mobile-list{display:grid;gap:12px}.mobile-item{display:grid;gap:8px;padding:14px;background:#fff;border:1px solid #e2e8f0;border-radius:12px}.mobile-item span{color:#64748b;font-size:13px}.manage-tabs :deep(.el-tabs__item){padding:0 10px}}
</style>
